### ISSUE TITLE
Why not initialize members?

### ISSUE THREAD

**Issue by szaghi** [MichaelSiehl/How-to-Code-Enumerations-in-Fortran#1]
@MichaelSiehl 

Dear Michael, very nice example, thank you for sharing it.

Just a curiosity: why [here](https://github.com/MichaelSiehl/How-to-Code-Enumerations-in-Fortran/blob/master/src/Fortran_Enum_Example.f90#L7) you avoid the members initialization? There are some constraints with some compilers? Maybe F90 does not support member initialization?

Cheers.

**Comment by MichaelSiehl** [comment]
Hi Stefano,
in principle, member initialization could be done since F95. But it would
not make much sense here, since the values get immediately overriden with
the declaration of the EnumColors constant:
TYPE (EnumColors_Values), PUBLIC, PARAMETER :: EnumColors =
EnumColors_Values (157839,230972,387150)

cheers

2016-10-18 11:53 GMT+02:00 Stefano Zaghi notifications@github.com:

**Comment by szaghi** [comment]
Hi Michael, yes I got the parameter overidding the initialization, it was only my OCD soul that let me to initialize all. So, F90 does not allow initialization very very interesting, thank you very much!

Cheers.

**Comment by MichaelSiehl** [comment]
Regarding initialization of variables in general see also Clerman/Spector:
Modern Fortran, style and usage, page 100:
"75. Do not initialize variables in their declarations unless necessary".
Of course, in many cases it is much safer to initialize.

cheers

2016-10-18 13:16 GMT+02:00 Stefano Zaghi notifications@github.com:

**Comment by szaghi** [comment]
@MichaelSiehl I read the book, but missed this sentence! Thank you again!
